# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_controller_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller_controller:
  ros__parameters:
    joint: joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_controller_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity